### ISSUE TITLE
Change Repository.sol's package's visiblity 

### ISSUE THREAD

**Issue by theMistletoe** [dev-protocol/repository-token#10]
# Description

It is a trivial thing.
Repository.sol's "package" is "public" visiblity.
In solidity, For public state variables, an automatic getter function is generated.
https://solidity.readthedocs.io/en/v0.4.24/contracts.html#visibility-and-getters
In the code, The other getter function is implemented, so that's duplecate code.

https://github.com/dev-protocol/repository-token/blob/master/contracts/Repository.sol

# Solution

Remove "public" on package.

# Alternatives/Features

I don't have any idea.

# Dev Challenge

Entry to [Dev Challenge](https://github.com/dev-protocol/repository-token/blob/master/docs/DEV_CHALLENGE.md).

- [x] I entry to Dev Challenge with this issue
- [ ] I don't enter to Dev Challenge with this issue

If you enter, please edit the following sections.

## Address

0x656b243D73911edAee87779125fEF90c2b1d781f

# Code of Conduct

By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/repository-token/blob/master/CODE_OF_CONDUCT.md) 🖖

**Comment by aggre** [comment]
Thank you for the refactoring proposal.

> In solidity, For public state variables, an automatic getter function is generated.

I overlooked this specification.

I think better remove a getter method, and keep variables "public." 
What do you think about it?

**Comment by theMistletoe** [comment]
I agree with you.
In that case, there are similar implementation in contract codes.
(Like State.sol)
Can I try to make pull request about this?
I'll try to fix including the others codes.

**Comment by aggre** [comment]
@theMistletoe Yeah, sure!

Refactoring is always very important.

**Comment by theMistletoe** [comment]
@aggre I made #12 
I think I have to make Distributor.sol's test, but it's difficult for me...

**Comment by aggre** [comment]
Thank you! Closes this issue by #12 .

> I think I have to make Distributor.sol's test, but it's difficult for me...

Yeah, I think too, Distributor's test is difficult.

There can be also expanded already exists test.

I should create issues, but I haven't created yet it. You can start from where you can!
